services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio-network
      - spark-network
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data

  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
    networks:
      - minio-network
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/lakehouse;
      /usr/bin/mc mb minio/lakehouse;
      /usr/bin/mc policy set public minio/lakehouse;
      tail -f /dev/null
      "

networks:
  minio-network:
    name: minio_network
    driver: bridge
  spark-network:
    name: spark_network
    external: true
